# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestConsultaporIdloslibrosprestados():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_consultaporIdloslibrosprestados(self):
    self.driver.get("http://localhost:53922/")
    self.driver.set_window_size(1041, 804)
    self.driver.find_element(By.NAME, "correo").click()
    self.driver.find_element(By.NAME, "correo").send_keys("Konoe@gmail.com")
    self.driver.find_element(By.NAME, "clave").send_keys("123")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".nav-item:nth-child(6) span").click()
    self.driver.find_element(By.LINK_TEXT, "Consultar").click()
    self.driver.find_element(By.ID, "cboestadoprestamo").click()
    self.driver.find_element(By.ID, "cbolectores").click()
    dropdown = self.driver.find_element(By.ID, "cbolectores")
    dropdown.find_element(By.XPATH, "//option[. = 'LE000009']").click()
    element = self.driver.find_element(By.ID, "btnbuscar")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "btnbuscar")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "btnbuscar")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.ID, "btnbuscar").click()
  
