# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestHacerunprestamo():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_hacerunprestamo(self):
    self.driver.get("http://localhost:53922/")
    self.driver.set_window_size(1049, 804)
    self.driver.find_element(By.NAME, "correo").click()
    self.driver.find_element(By.NAME, "correo").send_keys("Konoe@gmail.com")
    self.driver.find_element(By.NAME, "clave").send_keys("123")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Prestamos").click()
    self.driver.find_element(By.LINK_TEXT, "Regitrar").click()
    self.driver.find_element(By.ID, "btnbuscarlector").click()
    self.driver.find_element(By.CSS_SELECTOR, ".even .btn-select-lector > .fas").click()
    self.driver.find_element(By.ID, "btnbuscarlibro").click()
    element = self.driver.find_element(By.ID, "btnbuscarlibro")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".odd:nth-child(1) .btn-select-libro > .fas").click()
    self.driver.find_element(By.ID, "txtfechadevolucion").click()
    self.driver.find_element(By.LINK_TEXT, "30").click()
    self.driver.find_element(By.ID, "btnregistrar").click()
    self.driver.find_element(By.ID, "txtestadolibro").click()
    self.driver.find_element(By.ID, "txtestadolibro").send_keys("Muy bien")
    self.driver.find_element(By.ID, "btnGuardarRegistro").click()
    self.driver.find_element(By.CSS_SELECTOR, ".swal-button").click()
  
