# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBucarlibrosporcategoria():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_bucarlibrosporcategoria(self):
    self.driver.get("http://localhost:53922/")
    self.driver.set_window_size(1037, 804)
    self.driver.find_element(By.NAME, "correo").click()
    self.driver.find_element(By.NAME, "correo").send_keys("Konoe@gmail.com")
    self.driver.find_element(By.NAME, "clave").send_keys("123")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Biblioteca").click()
    self.driver.find_element(By.LINK_TEXT, "Categoria").click()
    self.driver.find_element(By.CSS_SELECTOR, "#tabla_filter .form-control").click()
    self.driver.find_element(By.CSS_SELECTOR, "#tabla_filter .form-control").send_keys("Amor")
  
