# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRegistrarunempleado():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_registrarunempleado(self):
    self.driver.get("http://localhost:53922/")
    self.driver.set_window_size(1041, 804)
    self.driver.find_element(By.NAME, "correo").click()
    self.driver.find_element(By.NAME, "correo").send_keys("Konoe@gmail.com")
    self.driver.find_element(By.NAME, "clave").send_keys("123")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Biblioteca").click()
    self.driver.find_element(By.CSS_SELECTOR, ".nav-item:nth-child(8) span").click()
    self.driver.find_element(By.LINK_TEXT, "Usuarios").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-success").click()
    self.driver.find_element(By.ID, "txtnombre").click()
    self.driver.find_element(By.ID, "txtnombre").send_keys("Luis")
    self.driver.find_element(By.ID, "txtapellido").click()
    self.driver.find_element(By.ID, "txtapellido").send_keys("Clase")
    self.driver.find_element(By.ID, "txtcorreo").click()
    self.driver.find_element(By.ID, "txtcorreo").send_keys("luisclase")
    self.driver.find_element(By.CSS_SELECTOR, "#formNivel > .row:nth-child(3) > .col-sm-12").click()
    self.driver.find_element(By.ID, "txtcorreo").click()
    self.driver.find_element(By.ID, "txtcorreo").send_keys("luisclase@gmail.com")
    self.driver.find_element(By.ID, "txtclave").click()
    self.driver.find_element(By.ID, "txtclave").send_keys("123")
    self.driver.find_element(By.ID, "cbotipo").click()
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(5) .form-group").click()
    self.driver.find_element(By.ID, "cbotipo").click()
    dropdown = self.driver.find_element(By.ID, "cbotipo")
    dropdown.find_element(By.XPATH, "//option[. = 'Empleado']").click()
    self.driver.find_element(By.ID, "cboEstado").click()
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(5) > .col-sm-12").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary:nth-child(2)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn-primary:nth-child(2)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
  
